### ISSUE TITLE
Check for flag.Parse error

### ISSUE THREAD

**Issue by kargakis** [brtzsnr/celtusminer#4]
I am suggesting to check for errors when parsing flags.

**Comment by kargakis** [comment]
Turns out it's not the best suggestion ever (at least in my [use](https://github.com/kargakis/cryptowallet/commit/2f7c356b41343be8f7ff546fa2cdb5a1b4019df2) case). I was striving for correctness with my cli tools but most if not all of the uses of `flag.Parse` I have seen in others code, nobody checks for that error. I am closing this, feel free to comment on it, reopen it, etc

**Comment by brtzsnr** [comment]
Thanks for checking the library. flag.Parse() doesn't return an error and, afaiu, it already prints usage when the command line flags are wrong (e.g. typo in flag name, string instead of int). However a better practice is to put flag.Parse() in main, not in init().

**Comment by kargakis** [comment]
Oh yes, I am using a custom flag package. Hadn't even noticed that the official Parse is just a plain function.
